ENH: add SapI enzyme restriction sites
Edinburgh-Genome-Foundry/DnaWeaver pull request #10
Opened 2021-07-28 14:11 UTC by alexsongrj

DNAweaver is a cool library to perform golden gate assembly. We would like to introduce "SapI" restriction enzyme to Golden Gate, change code in below. it is working for our sequence. Might need a more random sequence to test this. welcome to further discuss one of the changes.

2021-07-28 14:26 UTC, jlerman44 commented
Below is a script I wrote where 100 random text fixtures are generated and then tested. It works so long as ```half_homology = 2```. If we let it evaluate to ```3 // 2 == 1``` per the code in the master branch we cannot get the output to pass design verification by dnacauldron.  @Zulko, can you see if this might make sense? Or if it would be bad for other designs to hardcode this to 2?

```python
import random
import dnaweaver as dw
from dnaweaver import TmSegmentSelector
import dnacauldron as dc
import pandas as pd
import os

from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from geneblocks import  sequences_are_circularly_equal

def DNA(length=int(), letters="CGTA"):
    return''.join(random.choices(letters, k=length))

NUM_TRIALS = 100

for i in range(0, NUM_TRIALS):
    sequences = {
        'part1': DNA(1000),
        'part2': DNA(1000),
        'part3': DNA(1000),
    }

    desired_sequence = sequences['part1'] + sequences['part2'] + sequences['part3']
    # make sure desired has no SapI site.
    desired_sequence = desired_sequence.replace('GCTCTTC', 'GCGGAGC').replace('GAAGAGC', 'GATTTTC')
    desired_sequence = dw.SequenceString(desired_sequence, metadata={"topology": 'circular'})

    oligos_company = dw.CommercialDnaOffer(
        "OligoCompany",
        sequence_constraints=[dw.SequenceLengthConstraint(max_length=200)],
        pricing=dw.PerBasepairPricing(0.1)
    )
    pcr_station = dw.PcrExtractionStation(
        name="PCR station",
        max_overhang_length=50,
        primers_supplier=oligos_company,
        sequences=sequences,
        homology_selector=TmSegmentSelector(min_tm=35, max_tm=70),
        extra_cost=5
    )
    assembly_station = dw.DnaAssemblyStation(
        name="Golden Gate assembly",
        assembly_method = dw.GoldenGateAssemblyMethod(
            enzyme='SapI',
            min_segment_length=100,
            max_segment_length=10000,
            wildcard_basepair='G',
            left_addition='TCCTAG',
            right_addition='CTAGGA',
        ),
        supplier=pcr_station,
        coarse_grain=5,
        fine_grain=None,
        logger='bar'
    )

    # THIS LINE WILL PRE-BLAST THE SEQUENCE TO ACCELERATE COMPUTATIONS.
    assembly_station.prepare_network_on_sequence(desired_sequence)

    # FIND AN ASSEMBLY PLAN AND PRINT IT.
    quote = assembly_station.get_quote(desired_sequence)
    print(quote)
    assembly_report = quote.to_assembly_plan_report()
    try:
        assembly_report.write_full_report(f"Design{i}")
        print("Success! See figure assembly_plans.png.")
    except Exception as e:
        print("Error encountered....")
        print(e)
        raise

    # now verify things are correct
    df = pd.read_csv(f'Design{i}/sequences.csv', sep=';')
    target_sequence = df[df.Source=="Golden Gate assembly"].Sequence.unique()[0]
    df = df[df.Source=='PCR station']

    parts = {}
    ids = []
    for _, row in df.iterrows():
        new_seq_record = SeqRecord(Seq(row.Sequence))
        new_seq_record.id = row.ID
        new_seq_record.description = row.ID
        new_seq_record.name = row.ID
        new_seq_record.annotations['topology'] = 'linear'
        parts[row.ID] = new_seq_record
        ids.append(row.ID)

    repository = dc.SequenceRepository(collections={'my_collection': parts})

    assembly = dc.Type2sRestrictionAssembly(parts=ids, enzyme='SapI')
    simulation = assembly.simulate(sequence_repository=repository)

    # Print the ID and length of the generated construct(s)
    for record in simulation.construct_records:
        print (record.id, len(record))

    # Get a list of dictionnaries with data on each construct
    constructs_data = simulation.compute_all_construct_data_dicts()

    report_writer = dc.AssemblyReportWriter(
        include_mix_graphs=True, include_part_plots=True
    )

    # Write a full report with sequences and figures in a zip.
    simulation.write_report(f"Design{i}", report_writer=report_writer)
    assert len(simulation.construct_records) == 1
    predicted_construct_record = simulation.construct_records[0]

    assert sequences_are_circularly_equal([predicted_construct_record, target_sequence])
    print("VALID!")
```

2021-07-29 06:07 UTC, Zulko commented
Thanks both! I'm not sure exactly what the underlying problem was but happy that your changes work. The problem with the hard-coded `2` is that it won't work for longer homologies (Golden Gate, yeast recombination etc.). This makes `test_circular_sequences.py` fail. Would it be possible to replace these lines with the following, which should still work for you, and makes the current tests pass?

```
half_homology = int(np.ceil(self.max_homology_size / 2))
```

Would it be possible to create a minimal test (e.g. based on the script above, but without the trials loop) to add to the test suite?

2021-07-29 17:10 UTC, jlerman44 commented
@Zulko, sounds good. @alexsongrj and I will make this change, add a minimal test, and ensure all other tests pass.

2021-08-02 06:14 UTC, alexsongrj commented
@Zulko we made a minimal test in test_spai_enzyme_restriction_site.py with a random sequence plasmid. Would you mind take a look? thanks:)

2021-08-02 14:34 UTC, Zulko requested changes
Much appreciated @alexsongrj. The test looks good but I have left a few comments and corrections, could you have a look?

2021-08-02 14:34 UTC, Zulko commented on tests/test_spai_enzyme_restriction_site.py
> +import random
I would suggest adding  `"""Test contributed by {github handle or email}"""` on the first line. It could help if one day the test was breaking for unknown reasons.

2021-08-02 14:34 UTC, Zulko commented on tests/test_spai_enzyme_restriction_site.py
> +import random
Also it looks like `random` is imported but never used.

2021-08-02 14:34 UTC, Zulko commented on tests/test_spai_enzyme_restriction_site.py
> +    assembly_report.write_full_report(f"Design")
The problem with this path is that it will create a folder wherever the script is run. Please generate a temporary folder with `tempfile` and write the report in it.

2021-08-02 14:34 UTC, Zulko commented on tests/test_spai_enzyme_restriction_site.py
> +        sequence_path = os.path.join("data", f"test_sequence_spai_restriction_{i}.fa")
This assumes that the tests are run from the `tests/` folder but the tests are actually run from the root. This should be `os.path.join('tests', 'data', ...)`

2021-08-02 14:34 UTC, Zulko commented on tests/test_spai_enzyme_restriction_site.py
> +    for i in range(1, 4):
nit: replace with `[1, 2, 3]` which is easier to read

2021-08-02 14:34 UTC, Zulko commented on tests/test_spai_enzyme_restriction_site.py
> +        sequnce = load_record(sequence_path)
Why `sequnce`?

2021-08-02 14:34 UTC, Zulko commented on tests/data/test_sequence_spai_restriction_1.fa
> +> random_sequence
Just a note that while this is acceptable, there is an easier way to use random sequences without needing a file, with

```
from dnachisel.biotools import random_dna_sequence
# also "from easydna import random_dna_sequence"
my_random_sequence = random_dna_sequence(1000, seed=123)
```

Dnachisel is already used in other tests so it doesn't add a dependency.

2021-08-02 14:34 UTC, Zulko commented on tests/test_spai_enzyme_restriction_site.py
> +    desired_sequence = desired_sequence.replace('GCTCTTC', 'GCGGAGC').replace('GAAGAGC', 'GATTTTC')
This line looks a bit long. Could you run the Black formatter on this file to format everything nicely.

2021-08-02 17:33 UTC, veghp commented on tests/test_spai_enzyme_restriction_site.py
> +import random
Good idea, perhaps we can also mention the github issue number as well.

2021-08-02 17:34 UTC, veghp commented on tests/test_spai_enzyme_restriction_site.py
> +    assembly_report.write_full_report(f"Design")
Here is an example on using tmpdir, in case this helps: https://github.com/Edinburgh-Genome-Foundry/DnaChisel/blob/master/tests/test_optimization_with_report.py#L18

2021-08-03 09:40 UTC, alexsongrj commented on tests/test_spai_enzyme_restriction_site.py
> +import random
@Zulko @veghp  thanks for your suggestion. replaced the first line with contribution comments.

2021-08-03 09:42 UTC, alexsongrj commented on tests/test_spai_enzyme_restriction_site.py
> +    assembly_report.write_full_report(f"Design")
@Zulko @veghp thanks for your suggestion. make a tmpdir to store the design output following that example.

2021-08-03 09:45 UTC, alexsongrj commented on tests/test_spai_enzyme_restriction_site.py
> +        sequence_path = os.path.join("data", f"test_sequence_spai_restriction_{i}.fa")
@Zulko We removed those files for random sequencing data and replaced them with dnachisel.random_dna_sequence() to generate the random sequence.

2021-08-03 09:46 UTC, alexsongrj commented on tests/test_spai_enzyme_restriction_site.py
> +    for i in range(1, 4):
Good call! that is a typo. changed:)

2021-08-03 09:46 UTC, alexsongrj commented on tests/test_spai_enzyme_restriction_site.py
> +        sequnce = load_record(sequence_path)
Good call! that is a typo. changed:)

2021-08-03 09:48 UTC, alexsongrj commented on tests/test_spai_enzyme_restriction_site.py
> +    for i in range(1, 4):
We removed this part of code because we change to use random_dna_sequence.

2021-08-03 09:50 UTC, alexsongrj commented on tests/data/test_sequence_spai_restriction_1.fa
> +> random_sequence
@Zulko  Thanks for your suggestion. We applied random_dna_sequence function to generate three random sequence fragments.
    sequences = {
        "fragment 1": random_dna_sequence(1000, seed=123),
        "fragment 2": random_dna_sequence(1000, seed=456),
        "fragment 3": random_dna_sequence(1000, seed=789),
    }

2021-08-03 09:50 UTC, alexsongrj commented on tests/test_spai_enzyme_restriction_site.py
> +    desired_sequence = desired_sequence.replace('GCTCTTC', 'GCGGAGC').replace('GAAGAGC', 'GATTTTC')
Yap we format the code based on Black fomatter

2021-08-05 02:45 UTC, jlerman44 commented on tests/test_spai_enzyme_restriction_site.py
> +    desired_sequence = desired_sequence.replace("GCTCTTC", "GCGGAGC").replace(
@alexsongrj - not be needed if dnachisel does this, right?

2021-08-05 02:55 UTC, alexsongrj commented on tests/test_spai_enzyme_restriction_site.py
> +    desired_sequence = desired_sequence.replace("GCTCTTC", "GCGGAGC").replace(
@jlerman44 yap you are right, we just need one of them. I remove the hard code replace and leave dnachisel Constrains to remove the restriction enzyme site.

2021-08-05 03:04 UTC, jlerman44 commented
@veghp - good to go?

2021-08-12 00:56 UTC, Zulko commented
This looks good to me. @veghp are you ok to merge and release?

2021-08-12 11:14 UTC, merged

2021-08-12 11:21 UTC, veghp commented
Missed the last question, but now merged and released. Also fixed a typo in the test file name. Thanks for the contribution!